<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410142248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points INT NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type_id INT NOT NULL, season_id INT NOT NULL, planet_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095AC54C8C93 ON activity (type_id)');
        $this->addSql('CREATE INDEX IDX_AC74095AA25E9820 ON activity (planet_id)');
        $this->addSql('CREATE INDEX idx_activity_season ON activity (season_id)');
        $this->addSql('CREATE TABLE activity_astronaut (activity_id INT NOT NULL, astronaut_id INT NOT NULL, PRIMARY KEY (activity_id, astronaut_id))');
        $this->addSql('CREATE INDEX IDX_BAB5915281C06096 ON activity_astronaut (activity_id)');
        $this->addSql('CREATE INDEX IDX_BAB59152D390014D ON activity_astronaut (astronaut_id)');
        $this->addSql('CREATE TABLE activity_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, base_points INT NOT NULL, description TEXT DEFAULT NULL, allows_multiple_participants BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8F1A8CBB989D9B62 ON activity_type (slug)');
        $this->addSql('CREATE TABLE astronaut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, photo VARCHAR(255) DEFAULT NULL, client VARCHAR(255) DEFAULT NULL, hobbies TEXT DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, total_points INT NOT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planet_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5DADB6E5A25E9820 ON astronaut (planet_id)');
        $this->addSql('CREATE INDEX idx_astronaut_name ON astronaut (last_name, first_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EMAIL ON astronaut (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GOOGLE_ID ON astronaut (google_id)');
        $this->addSql('CREATE TABLE astronaut_trophy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, astronaut_id INT NOT NULL, trophy_id INT NOT NULL, season_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4C2E8EAD390014D ON astronaut_trophy (astronaut_id)');
        $this->addSql('CREATE INDEX IDX_C4C2E8EAF59AEEEF ON astronaut_trophy (trophy_id)');
        $this->addSql('CREATE INDEX IDX_C4C2E8EA4EC001D1 ON astronaut_trophy (season_id)');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT NOT NULL, astronaut_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7C16B89171F7E88B ON event_participant (event_id)');
        $this->addSql('CREATE INDEX IDX_7C16B891D390014D ON event_participant (astronaut_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EVENT_ASTRONAUT ON event_participant (event_id, astronaut_id)');
        $this->addSql('CREATE TABLE grade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, min_points INT NOT NULL, icon VARCHAR(255) DEFAULT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_595AAE34989D9B62 ON grade (slug)');
        $this->addSql('CREATE INDEX idx_grade_min_points ON grade (min_points)');
        $this->addSql('CREATE TABLE planet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, photo VARCHAR(255) DEFAULT NULL, mantra TEXT DEFAULT NULL, color VARCHAR(7) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68136AA55E237E06 ON planet (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68136AA5989D9B62 ON planet (slug)');
        $this->addSql('CREATE TABLE planet_season_points (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_points INT NOT NULL, planet_id INT NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F1183DEBA25E9820 ON planet_season_points (planet_id)');
        $this->addSql('CREATE INDEX IDX_F1183DEB4EC001D1 ON planet_season_points (season_id)');
        $this->addSql('CREATE INDEX idx_psp_season_points ON planet_season_points (season_id, total_points)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PLANET_SEASON ON planet_season_points (planet_id, season_id)');
        $this->addSql('CREATE TABLE planet_trophy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, planet_id INT NOT NULL, trophy_id INT NOT NULL, season_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D37FF21A25E9820 ON planet_trophy (planet_id)');
        $this->addSql('CREATE INDEX IDX_8D37FF21F59AEEEF ON planet_trophy (trophy_id)');
        $this->addSql('CREATE INDEX IDX_8D37FF214EC001D1 ON planet_trophy (season_id)');
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE trophy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AC54C8C93 FOREIGN KEY (type_id) REFERENCES activity_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AA25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_astronaut ADD CONSTRAINT FK_BAB5915281C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity_astronaut ADD CONSTRAINT FK_BAB59152D390014D FOREIGN KEY (astronaut_id) REFERENCES astronaut (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE astronaut ADD CONSTRAINT FK_5DADB6E5A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE astronaut_trophy ADD CONSTRAINT FK_C4C2E8EAD390014D FOREIGN KEY (astronaut_id) REFERENCES astronaut (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE astronaut_trophy ADD CONSTRAINT FK_C4C2E8EAF59AEEEF FOREIGN KEY (trophy_id) REFERENCES trophy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE astronaut_trophy ADD CONSTRAINT FK_C4C2E8EA4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_participant ADD CONSTRAINT FK_7C16B89171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_participant ADD CONSTRAINT FK_7C16B891D390014D FOREIGN KEY (astronaut_id) REFERENCES astronaut (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_season_points ADD CONSTRAINT FK_F1183DEBA25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_season_points ADD CONSTRAINT FK_F1183DEB4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_trophy ADD CONSTRAINT FK_8D37FF21A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_trophy ADD CONSTRAINT FK_8D37FF21F59AEEEF FOREIGN KEY (trophy_id) REFERENCES trophy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_trophy ADD CONSTRAINT FK_8D37FF214EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AC54C8C93');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A4EC001D1');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AA25E9820');
        $this->addSql('ALTER TABLE activity_astronaut DROP CONSTRAINT FK_BAB5915281C06096');
        $this->addSql('ALTER TABLE activity_astronaut DROP CONSTRAINT FK_BAB59152D390014D');
        $this->addSql('ALTER TABLE astronaut DROP CONSTRAINT FK_5DADB6E5A25E9820');
        $this->addSql('ALTER TABLE astronaut_trophy DROP CONSTRAINT FK_C4C2E8EAD390014D');
        $this->addSql('ALTER TABLE astronaut_trophy DROP CONSTRAINT FK_C4C2E8EAF59AEEEF');
        $this->addSql('ALTER TABLE astronaut_trophy DROP CONSTRAINT FK_C4C2E8EA4EC001D1');
        $this->addSql('ALTER TABLE event_participant DROP CONSTRAINT FK_7C16B89171F7E88B');
        $this->addSql('ALTER TABLE event_participant DROP CONSTRAINT FK_7C16B891D390014D');
        $this->addSql('ALTER TABLE planet_season_points DROP CONSTRAINT FK_F1183DEBA25E9820');
        $this->addSql('ALTER TABLE planet_season_points DROP CONSTRAINT FK_F1183DEB4EC001D1');
        $this->addSql('ALTER TABLE planet_trophy DROP CONSTRAINT FK_8D37FF21A25E9820');
        $this->addSql('ALTER TABLE planet_trophy DROP CONSTRAINT FK_8D37FF21F59AEEEF');
        $this->addSql('ALTER TABLE planet_trophy DROP CONSTRAINT FK_8D37FF214EC001D1');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_astronaut');
        $this->addSql('DROP TABLE activity_type');
        $this->addSql('DROP TABLE astronaut');
        $this->addSql('DROP TABLE astronaut_trophy');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_participant');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE planet');
        $this->addSql('DROP TABLE planet_season_points');
        $this->addSql('DROP TABLE planet_trophy');
        $this->addSql('DROP TABLE season');
        $this->addSql('DROP TABLE trophy');
    }
}
