<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415144002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(170) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404555E237E06 ON client (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455989D9B62 ON client (slug)');
        $this->addSql('ALTER TABLE astronaut ADD client_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE astronaut DROP client');
        $this->addSql('ALTER TABLE astronaut ADD CONSTRAINT FK_5DADB6E519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5DADB6E519EB6921 ON astronaut (client_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE client');
        $this->addSql('ALTER TABLE astronaut DROP CONSTRAINT FK_5DADB6E519EB6921');
        $this->addSql('DROP INDEX IDX_5DADB6E519EB6921');
        $this->addSql('ALTER TABLE astronaut ADD client VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE astronaut DROP client_id');
    }
}
